"""Core enumeration types for OpenAgentSec governance and evaluation schemas.

PRD v4.0.2 Phase 1B:
- Severity: strict 5-level severity scale (never dynamically generated by models)
- PlannerMode: single evaluation planner mode
- ObservabilityState: observable, unobservable, partially_observable
- MaturityLevel: L1..L4 maturity requirement
- EnvironmentType: synthetic, test, staging, production
"""

from __future__ import annotations

from enum import Enum


class Severity(str, Enum):
    """Structured severity levels for policy invariants and deviations.
    
    PRD v4.0.2 §5: Severity is governance metadata and must NOT be dynamically
    scored by models.
    """
    INFORMATIONAL = "informational"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class PlannerMode(str, Enum):
    """Evaluation planner operational mode.
    
    PRD v4.0.2 §6: Single mode controlling how evaluation scenario generation
    and execution is planned.
    """
    MODEL_DRIVEN = "model_driven"
    RULE_DRIVEN = "rule_driven"
    GRAPH_ASSISTED = "graph_assisted"
    HYBRID = "hybrid"


class ObservabilityState(str, Enum):
    """Explicit observability classification for target attributes and signals.
    
    PRD v4.0.2 §7: Must explicitly distinguish observable, unobservable, and
    partially_observable. Missing/undeclared states must never be auto-filled.
    """
    OBSERVABLE = "observable"
    UNOBSERVABLE = "unobservable"
    PARTIALLY_OBSERVABLE = "partially_observable"


class MaturityLevel(str, Enum):
    """Evaluation objective required maturity level."""
    L1 = "L1"
    L2 = "L2"
    L3 = "L3"
    L4 = "L4"


class EnvironmentType(str, Enum):
    """Target deployment environment classification."""
    SYNTHETIC = "synthetic"
    TEST = "test"
    STAGING = "staging"
    PRODUCTION = "production"
