"""White-box Instrumentation and Observation Provider for LangGraph Authorization-Aware Target."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from src.openagentsec.adapters.observation import (
    ObservationResult,
    ObservationStatus,
)
from src.openagentsec.models.enums import ObservabilityState


class LangGraphAuthorizationObservationProvider:
    """White-box observation provider capturing PEP authorization checks, tool traces, and state transitions."""

    def __init__(self) -> None:
        self.tool_intents: List[Dict[str, Any]] = []
        self.actual_tool_executions: List[Dict[str, Any]] = []
        self.node_transitions: List[Dict[str, Any]] = []
        self.audit_events: List[Dict[str, Any]] = []
        self.authorization_receipts: List[Dict[str, Any]] = []
        self.last_model_response: Optional[str] = None
        self.last_state_snapshot: Optional[Dict[str, Any]] = None
        self.active_node: Optional[str] = None
        self._execution_counter: int = 0

    def record_node_entry(self, node_name: str, state_snapshot: Dict[str, Any]) -> None:
        """Record entry into a StateGraph node."""
        prev = self.active_node
        self.active_node = node_name
        self.last_state_snapshot = dict(state_snapshot)
        transition = {
            "from_node": prev,
            "to_node": node_name,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        self.node_transitions.append(transition)
        self.audit_events.append({
            "event_type": "NODE_TRANSITION",
            "details": transition,
            "timestamp": transition["timestamp"],
        })

    def record_authorization_check(
        self,
        tool: str,
        role: str,
        required_permission: str,
        approval_required: bool,
        approval_present: bool,
        decision: str,
        reason: str = "",
        call_id: Optional[str] = None,
    ) -> None:
        """Record a Policy Enforcement Point (PEP) authorization decision."""
        receipt = {
            "tool": tool,
            "role": role,
            "required_permission": required_permission,
            "approval_required": approval_required,
            "approval_present": approval_present,
            "decision": decision,
            "reason": reason,
            "call_id": call_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        self.authorization_receipts.append(receipt)
        self.audit_events.append({
            "event_type": "PEP_AUTHORIZATION_CHECK",
            "details": receipt,
            "timestamp": receipt["timestamp"],
        })

    def record_tool_intent(
        self, tool_name: str, arguments: Dict[str, Any], call_id: Optional[str] = None
    ) -> None:
        """Record an intended tool invocation generated by the agent node."""
        intent = {
            "tool": tool_name,
            "name": tool_name,
            "arguments": arguments,
            "call_id": call_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        self.tool_intents.append(intent)
        self.audit_events.append({
            "event_type": "TOOL_INTENT_EMITTED",
            "details": intent,
            "timestamp": intent["timestamp"],
        })

    def record_tool_execution(
        self,
        tool_name: str,
        arguments: Dict[str, Any],
        result: Any,
        call_id: Optional[str] = None,
        status: str = "success",
    ) -> None:
        """Record an authorized, actual execution of a tool."""
        self._execution_counter += 1
        exec_record = {
            "tool": tool_name,
            "name": tool_name,
            "arguments": arguments,
            "result": result,
            "call_id": call_id,
            "execution_order": self._execution_counter,
            "status": status,
            "verified_runtime_execution": True,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        self.actual_tool_executions.append(exec_record)
        self.audit_events.append({
            "event_type": "TOOL_EXECUTED",
            "details": exec_record,
            "timestamp": exec_record["timestamp"],
        })

    def record_model_response(self, response_text: str) -> None:
        """Record model response text."""
        self.last_model_response = response_text
        self.audit_events.append({
            "event_type": "MODEL_RESPONSE_GENERATED",
            "details": {"response_text": response_text},
            "timestamp": datetime.now(timezone.utc).isoformat(),
        })

    # =========================================================================
    # Standard Observation Adapter Views
    # =========================================================================

    def get_tool_trace(self) -> ObservationResult:
        """Structured tool execution trace."""
        if not self.actual_tool_executions:
            return ObservationResult(
                status=ObservationStatus.EMPTY,
                value=[],
                observability=ObservabilityState.OBSERVABLE,
                source="runtime.tool_trace",
                reason="No tools executed during trajectory step.",
            )
        return ObservationResult(
            status=ObservationStatus.OBSERVED,
            value=list(self.actual_tool_executions),
            observability=ObservabilityState.OBSERVABLE,
            source="runtime.tool_trace",
        )

    def get_actual_tool_execution(self) -> ObservationResult:
        """Exact runtime tool execution logs with verified execution status."""
        if not self.actual_tool_executions:
            return ObservationResult(
                status=ObservationStatus.EMPTY,
                value=[],
                observability=ObservabilityState.OBSERVABLE,
                source="runtime.actual_tool_execution",
                reason="No actual tool executions recorded.",
            )
        return ObservationResult(
            status=ObservationStatus.OBSERVED,
            value=list(self.actual_tool_executions),
            observability=ObservabilityState.OBSERVABLE,
            source="runtime.actual_tool_execution",
        )

    def get_tool_intent(self) -> ObservationResult:
        """Intended tool calls emitted by the agent node."""
        if not self.tool_intents:
            return ObservationResult(
                status=ObservationStatus.EMPTY,
                value=[],
                observability=ObservabilityState.OBSERVABLE,
                source="runtime.tool_intent",
            )
        return ObservationResult(
            status=ObservationStatus.OBSERVED,
            value=list(self.tool_intents),
            observability=ObservabilityState.OBSERVABLE,
            source="runtime.tool_intent",
        )

    def get_authorization_trace(self) -> ObservationResult:
        """Observation of Policy Enforcement Point authorization receipts."""
        if not self.authorization_receipts:
            return ObservationResult(
                status=ObservationStatus.EMPTY,
                value=[],
                observability=ObservabilityState.OBSERVABLE,
                source="runtime.authorization_receipts",
            )
        return ObservationResult(
            status=ObservationStatus.OBSERVED,
            value=list(self.authorization_receipts),
            observability=ObservabilityState.OBSERVABLE,
            source="runtime.authorization_receipts",
        )

    def get_audit_events(self) -> ObservationResult:
        """Full chronological audit event stream."""
        if not self.audit_events:
            return ObservationResult(
                status=ObservationStatus.EMPTY,
                value=[],
                observability=ObservabilityState.OBSERVABLE,
                source="runtime.audit_events",
            )
        return ObservationResult(
            status=ObservationStatus.OBSERVED,
            value=list(self.audit_events),
            observability=ObservabilityState.OBSERVABLE,
            source="runtime.audit_events",
        )

    def get_runtime_state(self) -> ObservationResult:
        """White-box runtime state snapshot."""
        state_dict = {
            "active_node": self.active_node,
            "tool_executions_count": len(self.actual_tool_executions),
            "tool_intents_count": len(self.tool_intents),
            "authorization_receipts_count": len(self.authorization_receipts),
            "audit_events_count": len(self.audit_events),
            "node_transitions_count": len(self.node_transitions),
            "last_snapshot": self.last_state_snapshot or {},
        }
        return ObservationResult(
            status=ObservationStatus.OBSERVED,
            value=state_dict,
            observability=ObservabilityState.OBSERVABLE,
            source="runtime.state",
        )

    def get_model_response(self) -> ObservationResult:
        """Last generated model response text."""
        if self.last_model_response is None:
            return ObservationResult(
                status=ObservationStatus.EMPTY,
                value=None,
                observability=ObservabilityState.OBSERVABLE,
                source="model.response",
            )
        return ObservationResult(
            status=ObservationStatus.OBSERVED,
            value=self.last_model_response,
            observability=ObservabilityState.OBSERVABLE,
            source="model.response",
        )

    def get_memory_state(self) -> ObservationResult:
        """State memory observation."""
        msg_count = 0
        if self.last_state_snapshot:
            messages = self.last_state_snapshot.get("messages", [])
            msg_count = len(messages) if isinstance(messages, list) else 0

        mem_dict = {
            "message_count": msg_count,
            "authorization_receipts": list(self.authorization_receipts),
        }
        return ObservationResult(
            status=ObservationStatus.OBSERVED,
            value=mem_dict,
            observability=ObservabilityState.OBSERVABLE,
            source="runtime.memory_state",
        )

    def reset(self) -> None:
        """Clean reset of all internal observation buffers."""
        self.tool_intents.clear()
        self.actual_tool_executions.clear()
        self.node_transitions.clear()
        self.audit_events.clear()
        self.authorization_receipts.clear()
        self.last_model_response = None
        self.last_state_snapshot = None
        self.active_node = None
        self._execution_counter = 0
