"""EvaluationOperator domain model (PRD v4.0.2 §10.3)."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List

from .enums import EvaluationOperatorType


@dataclass(frozen=True)
class EvaluationOperator:
    """Atomic evaluation action operator generated by Evaluation Planner."""

    operator_id: str
    operator_type: EvaluationOperatorType
    objective_id: str
    risk_refs: List[str] = field(default_factory=list)
    policy_refs: List[str] = field(default_factory=list)
    parameters: Dict[str, Any] = field(default_factory=dict)
    preconditions: List[str] = field(default_factory=list)
    expected_observations: List[str] = field(default_factory=list)
    safety_constraints: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.operator_id or not isinstance(self.operator_id, str):
            raise ValueError("operator_id must be a non-empty string")
        if not isinstance(self.operator_type, EvaluationOperatorType):
            if isinstance(self.operator_type, str):
                try:
                    object.__setattr__(self, "operator_type", EvaluationOperatorType(self.operator_type))
                except ValueError:
                    raise ValueError(f"Invalid operator_type '{self.operator_type}'")
            else:
                raise ValueError(f"operator_type must be an EvaluationOperatorType, got {type(self.operator_type)}")
        if not self.objective_id or not isinstance(self.objective_id, str):
            raise ValueError("objective_id must be a non-empty string")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "operator_id": self.operator_id,
            "operator_type": self.operator_type.value,
            "objective_id": self.objective_id,
            "risk_refs": list(self.risk_refs),
            "policy_refs": list(self.policy_refs),
            "parameters": dict(self.parameters),
            "preconditions": list(self.preconditions),
            "expected_observations": list(self.expected_observations),
            "safety_constraints": list(self.safety_constraints),
            "metadata": dict(self.metadata),
        }
