"""ScenarioPlan domain model and deterministic hashing (PRD v4.0.2 §10 & §11)."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
import hashlib
import json
from typing import Any, Dict, List, Optional

from ..models.enums import PlannerMode
from .operator import EvaluationOperator


def compute_plan_hash(payload: Dict[str, Any]) -> str:
    """Compute deterministic SHA-256 hash over canonical JSON representation."""
    canonical_json = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical_json.encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class ScenarioPlan:
    """Structured evaluation scenario plan generated by Evaluation Planner.
    
    PRD v4.0.2 §10:
    Answers 'WHAT SHOULD WE TRY?' and outputs planned operators and safety constraints.
    Does NOT contain execution results, pass/fail status, or severity scores.
    """

    scenario_id: str
    objective_id: str
    policy_refs: List[str]
    risk_refs: List[str]
    target_id: str
    planner_mode: PlannerMode
    operators: List[EvaluationOperator] = field(default_factory=list)
    scenario_seed_ref: Optional[str] = None
    seed_metadata: Dict[str, Any] = field(default_factory=dict)
    required_observations: List[str] = field(default_factory=list)
    required_evidence: List[str] = field(default_factory=list)
    safety_constraints: List[str] = field(default_factory=list)
    max_steps: int = 10
    stop_conditions: List[str] = field(default_factory=list)
    deterministic_plan_hash: str = ""
    limitations: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def __post_init__(self) -> None:
        if not self.scenario_id or not isinstance(self.scenario_id, str):
            raise ValueError("scenario_id must be a non-empty string")
        if not self.objective_id or not isinstance(self.objective_id, str):
            raise ValueError("objective_id must be a non-empty string")
        if not self.target_id or not isinstance(self.target_id, str):
            raise ValueError("target_id must be a non-empty string")
        if not isinstance(self.planner_mode, PlannerMode):
            if isinstance(self.planner_mode, str):
                try:
                    object.__setattr__(self, "planner_mode", PlannerMode(self.planner_mode))
                except ValueError:
                    raise ValueError(f"Invalid planner_mode '{self.planner_mode}'")
            else:
                raise ValueError(f"planner_mode must be a PlannerMode, got {type(self.planner_mode)}")

    def get_semantic_hash_payload(self) -> Dict[str, Any]:
        """Extract canonical semantic payload excluding identity-derived fields."""
        return {
            "planner_mode": self.planner_mode.value,
            "objective_id": self.objective_id,
            "target_id": self.target_id,
            "policy_refs": sorted(list(self.policy_refs)),
            "risk_refs": sorted(list(self.risk_refs)),
            "operators": [
                {
                    "operator_type": op.operator_type.value,
                    "parameters": op.parameters,
                    "expected_observations": sorted(list(op.expected_observations)),
                    "safety_constraints": sorted(list(op.safety_constraints)),
                }
                for op in self.operators
            ],
            "required_observations": sorted(list(self.required_observations)),
            "required_evidence": sorted(list(self.required_evidence)),
            "safety_constraints": sorted(list(self.safety_constraints)),
            "max_steps": self.max_steps,
            "stop_conditions": sorted(list(self.stop_conditions)),
            "config": dict(self.metadata.get("config", {})),
        }

    def recompute_hash(self) -> str:
        """Recompute deterministic hash from the final semantic plan content."""
        return compute_plan_hash(self.get_semantic_hash_payload())

    def to_dict(self) -> Dict[str, Any]:
        return {
            "scenario_id": self.scenario_id,
            "objective_id": self.objective_id,
            "policy_refs": list(self.policy_refs),
            "risk_refs": list(self.risk_refs),
            "target_id": self.target_id,
            "planner_mode": self.planner_mode.value,
            "operators": [op.to_dict() for op in self.operators],
            "scenario_seed_ref": self.scenario_seed_ref,
            "seed_metadata": dict(self.seed_metadata),
            "required_observations": list(self.required_observations),
            "required_evidence": list(self.required_evidence),
            "safety_constraints": list(self.safety_constraints),
            "max_steps": self.max_steps,
            "stop_conditions": list(self.stop_conditions),
            "deterministic_plan_hash": self.deterministic_plan_hash,
            "limitations": list(self.limitations),
            "metadata": dict(self.metadata),
            "created_at": self.created_at,
        }
