"""White-box Instrumentation and Observation Provider for LangGraph MVP-1 Target."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from src.openagentsec.adapters.observation import (
    ObservationResult,
    ObservationStatus,
)
from src.openagentsec.models.enums import ObservabilityState


class LangGraphObservationProvider:
    """White-box observation provider for LangGraph execution runtime."""

    def __init__(self) -> None:
        self.tool_intents: List[Dict[str, Any]] = []
        self.actual_tool_executions: List[Dict[str, Any]] = []
        self.node_transitions: List[Dict[str, Any]] = []
        self.audit_events: List[Dict[str, Any]] = []
        self.last_model_response: Optional[str] = None
        self.last_state_snapshot: Optional[Dict[str, Any]] = None
        self.active_node: Optional[str] = None
        self._execution_counter: int = 0

    def record_node_entry(self, node_name: str, state_snapshot: Dict[str, Any]) -> None:
        """Record entry into a StateGraph node."""
        prev = self.active_node
        self.active_node = node_name
        self.last_state_snapshot = dict(state_snapshot)
        transition = {
            "from_node": prev,
            "to_node": node_name,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        self.node_transitions.append(transition)
        self.audit_events.append({
            "event_type": "NODE_TRANSITION",
            "details": transition,
            "timestamp": transition["timestamp"],
        })

    def record_tool_intent(self, tool_name: str, args: Dict[str, Any], call_id: str) -> None:
        """Record a structured tool intent generated by the model (AIMessage.tool_calls)."""
        intent = {
            "tool": tool_name,
            "args": args,
            "call_id": call_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "source": "model_output_intent",
        }
        self.tool_intents.append(intent)
        self.audit_events.append({
            "event_type": "TOOL_INTENT_GENERATED",
            "details": intent,
            "timestamp": intent["timestamp"],
        })

    def record_tool_execution(
        self,
        tool_name: str,
        args: Dict[str, Any],
        call_id: str,
        status: str,
        result: Any,
    ) -> None:
        """Record actual tool execution in the LangGraph tool execution path."""
        self._execution_counter += 1
        record = {
            "execution_order": self._execution_counter,
            "tool": tool_name,
            "args": args,
            "call_id": call_id,
            "status": status,
            "result": result,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "verified_runtime_execution": True,
        }
        self.actual_tool_executions.append(record)
        self.audit_events.append({
            "event_type": "ACTUAL_TOOL_EXECUTED",
            "details": record,
            "timestamp": record["timestamp"],
        })

    def record_model_response(self, response_text: str) -> None:
        """Record final assistant response message."""
        self.last_model_response = response_text
        self.audit_events.append({
            "event_type": "MODEL_RESPONSE_GENERATED",
            "details": {"response": response_text},
            "timestamp": datetime.now(timezone.utc).isoformat(),
        })

    def get_model_response(self) -> ObservationResult[Optional[str]]:
        if self.last_model_response is None:
            return ObservationResult(
                observability=ObservabilityState.OBSERVABLE,
                status=ObservationStatus.EMPTY,
                value=None,
                source="langgraph_whitebox_instrumentation",
                reason="No model response generated yet",
            )
        return ObservationResult(
            observability=ObservabilityState.OBSERVABLE,
            status=ObservationStatus.OBSERVED,
            value=self.last_model_response,
            source="langgraph_whitebox_instrumentation",
        )

    def get_tool_trace(self) -> ObservationResult[Optional[List[Dict[str, Any]]]]:
        if not self.actual_tool_executions:
            return ObservationResult(
                observability=ObservabilityState.OBSERVABLE,
                status=ObservationStatus.EMPTY,
                value=[],
                source="langgraph_whitebox_instrumentation",
                reason="No tool executions occurred",
            )
        return ObservationResult(
            observability=ObservabilityState.OBSERVABLE,
            status=ObservationStatus.OBSERVED,
            value=list(self.actual_tool_executions),
            source="langgraph_whitebox_instrumentation",
        )

    def get_runtime_state(self) -> ObservationResult[Optional[Dict[str, Any]]]:
        if not self.node_transitions:
            return ObservationResult(
                observability=ObservabilityState.OBSERVABLE,
                status=ObservationStatus.EMPTY,
                value=None,
                source="langgraph_whitebox_instrumentation",
                reason="Graph has not executed yet",
            )
        return ObservationResult(
            observability=ObservabilityState.OBSERVABLE,
            status=ObservationStatus.OBSERVED,
            value={
                "active_node": self.active_node,
                "node_transitions": list(self.node_transitions),
                "total_transitions": len(self.node_transitions),
                "latest_snapshot": self.last_state_snapshot,
            },
            source="langgraph_whitebox_instrumentation",
        )

    def get_memory_state(self) -> ObservationResult[Optional[Dict[str, Any]]]:
        if self.last_state_snapshot is None:
            return ObservationResult(
                observability=ObservabilityState.OBSERVABLE,
                status=ObservationStatus.EMPTY,
                value={"messages": [], "message_count": 0},
                source="langgraph_whitebox_instrumentation",
                reason="No checkpoint state recorded",
            )
        msgs = self.last_state_snapshot.get("messages", [])
        return ObservationResult(
            observability=ObservabilityState.OBSERVABLE,
            status=ObservationStatus.OBSERVED,
            value={
                "messages": [str(m) for m in msgs],
                "message_count": len(msgs),
                "untrusted_context_retrieved": self.last_state_snapshot.get(
                    "untrusted_context_retrieved", False
                ),
            },
            source="langgraph_whitebox_instrumentation",
        )

    def get_audit_events(self) -> ObservationResult[Optional[List[Dict[str, Any]]]]:
        if not self.audit_events:
            return ObservationResult(
                observability=ObservabilityState.OBSERVABLE,
                status=ObservationStatus.EMPTY,
                value=[],
                source="langgraph_whitebox_instrumentation",
            )
        return ObservationResult(
            observability=ObservabilityState.OBSERVABLE,
            status=ObservationStatus.OBSERVED,
            value=list(self.audit_events),
            source="langgraph_whitebox_instrumentation",
        )

    def reset(self) -> ObservationResult[bool]:
        """Reset instrumentation collectors and verify clean state."""
        self.tool_intents.clear()
        self.actual_tool_executions.clear()
        self.node_transitions.clear()
        self.audit_events.clear()
        self.last_model_response = None
        self.last_state_snapshot = None
        self.active_node = None
        self._execution_counter = 0

        # Self-check baseline restoration
        is_clean = (
            len(self.tool_intents) == 0
            and len(self.actual_tool_executions) == 0
            and len(self.node_transitions) == 0
            and len(self.audit_events) == 0
            and self.last_model_response is None
        )
        if not is_clean:
            return ObservationResult(
                observability=ObservabilityState.OBSERVABLE,
                status=ObservationStatus.ERROR,
                value=None,
                source="langgraph_whitebox_instrumentation",
                reason="Failed to restore clean baseline in instrumentation provider",
            )

        return ObservationResult(
            observability=ObservabilityState.OBSERVABLE,
            status=ObservationStatus.OBSERVED,
            value=True,
            source="langgraph_whitebox_instrumentation",
        )
