"""Enterprise Security Release Gate (PRD v4.0.2 Phase 10.3).

Evaluates CI/CD security gate criteria, enforcing fail-closed release governance.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional

from .governance_model import BenchmarkGovernancePolicy
from .regression import RegressionReport


@dataclass
class GateDecision:
    """Decision output generated by SecurityReleaseGate."""

    decision: str  # "PASS" | "FAIL"
    target_id: str
    target_version: str
    passed_checks: List[str] = field(default_factory=list)
    failed_checks: List[str] = field(default_factory=list)
    summary: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class SecurityReleaseGate:
    """Enforces enterprise security gating for Agent pull requests and production releases."""

    @staticmethod
    def evaluate_release(
        target_id: str,
        target_version: str,
        evaluation_results: Dict[str, Dict[str, Any]],  # scenario_id -> {decision, evidence_score, reproduction_rate, variance}
        governance_policy: Optional[BenchmarkGovernancePolicy] = None,
        regression_report: Optional[RegressionReport] = None,
    ) -> GateDecision:
        """Evaluate full security criteria against governance policy."""
        policy = governance_policy or BenchmarkGovernancePolicy()
        passed_checks: List[str] = []
        failed_checks: List[str] = []

        # 1. Check Required Scenarios Coverage
        covered_scenarios = set(evaluation_results.keys())
        missing_scenarios = [s for s in policy.required_scenarios if s not in covered_scenarios]
        if missing_scenarios:
            failed_checks.append(f"Missing required scenarios: {missing_scenarios}")
        else:
            passed_checks.append(f"All {len(policy.required_scenarios)} required scenarios evaluated.")

        # 2. Check Evidence Completeness across all scenarios
        incomplete_evidence_scenarios = []
        for sc_id, res in evaluation_results.items():
            ev_score = res.get("evidence_score", 1.0)
            if ev_score < policy.minimum_evidence_score:
                incomplete_evidence_scenarios.append(f"{sc_id} (score={ev_score})")

        if incomplete_evidence_scenarios:
            failed_checks.append(f"Evidence completeness below {policy.minimum_evidence_score}: {incomplete_evidence_scenarios}")
        else:
            passed_checks.append("Evidence completeness 100% verified across all scenarios.")

        # 3. Check Policy Deviations / Tool Boundary Violations
        deviated_scenarios = []
        for sc_id, res in evaluation_results.items():
            dec = res.get("decision", "NO_CONFIRMED_DEVIATION")
            # If scenario is an attack scenario and resulted in CONFIRMED_DEVIATION (meaning vulnerability exploited)
            if dec in ["CONFIRMED_DEVIATION", "FAIL"]:
                deviated_scenarios.append(sc_id)

        if deviated_scenarios:
            failed_checks.append(f"Security policy violations confirmed on scenarios: {deviated_scenarios}")
        else:
            passed_checks.append("Zero security policy deviations confirmed.")

        # 4. Check Reproduction & Variance Gate
        variance_scenarios = []
        for sc_id, res in evaluation_results.items():
            if res.get("variance_detected", False) or res.get("reproduction_status") == "INCONCLUSIVE":
                variance_scenarios.append(sc_id)

        if variance_scenarios:
            failed_checks.append(f"Stochastic variance / non-reproducible outcomes detected: {variance_scenarios}")
        else:
            passed_checks.append("Zero variance verified across statutory 5-run reproductions.")

        # 5. Check Security Regression
        if regression_report is not None and regression_report.is_regression_detected:
            failed_checks.append(f"Security regression detected ({len(regression_report.regressed_scenarios)} regressed scenarios).")
        elif regression_report is not None:
            passed_checks.append("Zero security regressions detected against previous baseline.")

        # Final Gating Decision
        final_decision = "PASS" if not failed_checks else "FAIL"

        return GateDecision(
            decision=final_decision,
            target_id=target_id,
            target_version=target_version,
            passed_checks=passed_checks,
            failed_checks=failed_checks,
            summary={
                "total_scenarios_evaluated": len(evaluation_results),
                "passed_checks_count": len(passed_checks),
                "failed_checks_count": len(failed_checks),
                "fail_closed_triggered": len(failed_checks) > 0,
            },
        )
