#!/usr/bin/env python3
"""Phase-93E Handoff Schema Validator — 仅验证交接包字段完整性"""
import os, sys, yaml
HANDOFF = os.path.join(os.path.dirname(__file__), "..", "docs", "phase93e_evidence_handoff_package.yaml")
checks = []; P = 0; F = 0
def check(d, c):
    global P, F; checks.append((d,c))
    if c: P += 1; print(f"  ✅ {d}")
    else: F += 1; print(f"  ❌ {d}")

print("\n=== Phase-93E Handoff Schema Validator ===")
check("handoff file exists", os.path.exists(HANDOFF))
pkg = yaml.safe_load(open(HANDOFF))
check("package_id present", pkg.get("package_id") is not None)
check("registry_diff_lines=0", pkg.get("registry_diff_lines") == 0)

# === RED-018 ===
print("\n--- RED-018 ---")
r18 = pkg.get("red_018", {})
check("task_id", r18.get("task_id") == "RED-018")
check("task_type", r18.get("task_type") == "red_team_action_report")
check("assessment_mode", r18.get("assessment_mode") == "adversarial_validation")
check("prd_reference present", r18.get("prd_reference") is not None)
check("actual_artifacts_summary present", len(r18.get("actual_artifacts_summary", [])) > 0)
check("validator_name", r18.get("validator_name") == "validate_red018.py")
check("validator_passed_count=19", r18.get("validator_passed_count") == 19)
check("validator_failed_count=0", r18.get("validator_failed_count") == 0)
check("all_checks_passed_claimed=true", r18.get("all_checks_passed_claimed") is True)
check("execution_results_present=true", r18.get("execution_results_present") is True)
check("execution_results_modified=false", r18.get("execution_results_modified") is False)
check("execution_results_integrity_verified=true", r18.get("execution_results_integrity_verified") is True)
check("coverage_change_claimed=false", r18.get("coverage_change_claimed") is False)
check("registry_diff_verified=true", r18.get("registry_diff_verified") is True)
check("safety_fields_verified=true", r18.get("safety_fields_verified") is True)
check("execution_allowed=false", r18.get("execution_allowed") is False)
check("all_findings_are_candidate_level=true", r18.get("all_findings_are_candidate_level") is True)
sf18 = r18.get("safety_fields", {})
check("confirmed_vulnerability=false", sf18.get("confirmed_vulnerability") is False)
check("formal_finding_allowed=false", sf18.get("formal_finding_allowed") is False)
check("production_safety_claimed=false", sf18.get("production_safety_claimed") is False)
check("attack_execution_allowed=false", sf18.get("attack_execution_allowed") is False)
check("synthetic_only=true", sf18.get("synthetic_only") is True)
check("red_team_engine_not_executable=true", sf18.get("red_team_engine_not_executable") is True)
check("dashboard_not_execution_interface=true", sf18.get("dashboard_not_execution_interface") is True)
check("selected_attack_surface present", len(r18.get("selected_attack_surface", [])) > 0)
check("selected_modules present", len(r18.get("selected_modules", [])) > 0)
check("selected_paths present", r18.get("selected_paths") is not None)
check("attack_chain_execution_summary present", r18.get("attack_chain_execution_summary") is not None)
check("defense_degradation_trajectory present", r18.get("defense_degradation_trajectory") is not None)
check("key_findings_count present", r18.get("key_findings_count") is not None)
check("red_team_evidence_candidates_count present", r18.get("red_team_evidence_candidates_count") is not None)
check("blue_control_candidates_count present", r18.get("blue_control_candidates_count") is not None)
check("purple_retest_candidates_count present", r18.get("purple_retest_candidates_count") is not None)
check("human_review_gate=true", r18.get("human_review_gate") is True)

# === RED-019 ===
print("\n--- RED-019 ---")
r19 = pkg.get("red_019", {})
check("task_id", r19.get("task_id") == "RED-019")
check("task_type", r19.get("task_type") == "red_team_action_report")
check("validator_name", r19.get("validator_name") == "validate_red019.py")
check("validator_passed_count=13", r19.get("validator_passed_count") == 13)
check("validator_failed_count=0", r19.get("validator_failed_count") == 0)
check("execution_results_modified=false", r19.get("execution_results_modified") is False)
check("coverage_change_claimed=false", r19.get("coverage_change_claimed") is False)
check("safety_fields_verified=true", r19.get("safety_fields_verified") is True)
check("execution_allowed=false", r19.get("execution_allowed") is False)
sf19 = r19.get("safety_fields", {})
check("confirmed_vulnerability=false", sf19.get("confirmed_vulnerability") is False)
check("synthetic_only=true", sf19.get("synthetic_only") is True)

# === RED-020 ===
print("\n--- RED-020 ---")
r20 = pkg.get("red_020", {})
check("task_id", r20.get("task_id") == "RED-020")
check("task_type", r20.get("task_type") == "red_team_action_report")
check("validator_name", r20.get("validator_name") == "validate_red020.py")
check("validator_passed_count=13", r20.get("validator_passed_count") == 13)
check("validator_failed_count=0", r20.get("validator_failed_count") == 0)
check("execution_results_modified=false", r20.get("execution_results_modified") is False)
check("coverage_change_claimed=false", r20.get("coverage_change_claimed") is False)
check("safety_fields_verified=true", r20.get("safety_fields_verified") is True)
check("execution_allowed=false", r20.get("execution_allowed") is False)
sf20 = r20.get("safety_fields", {})
check("confirmed_vulnerability=false", sf20.get("confirmed_vulnerability") is False)
check("synthetic_only=true", sf20.get("synthetic_only") is True)

# === FIXT-093A ===
print("\n--- FIXT-093A ---")
f93a = pkg.get("fixt_093a", {})
check("task_type=fixture_update", f93a.get("task_type") == "fixture_update")
check("registered_module=false", f93a.get("registered_module") is False)
check("shared_asset_task=true", f93a.get("shared_asset_task") is True)
check("synthetic_only=true", f93a.get("synthetic_only") is True)
check("capability_value=not_applicable", f93a.get("capability_value") == "not_applicable")
check("risk_level=not_applicable", f93a.get("risk_level") == "not_applicable")
check("coverage_change_claimed=false", f93a.get("coverage_change_claimed") is False)
check("confirmed_vulnerability=false", f93a.get("confirmed_vulnerability") is False)
check("formal_finding_allowed=false", f93a.get("formal_finding_allowed") is False)
check("assessment_execution_performed=false", f93a.get("assessment_execution_performed") is False)
check("capability_engine_executed=false", f93a.get("capability_engine_executed") is False)
check("execution_results_generated=false", f93a.get("execution_results_generated") is False)
check("execution_allowed=false", f93a.get("execution_allowed") is False)
check("validator_name", f93a.get("validator_name") == "validate_fixt093a.py")
check("validator_passed_count=13", f93a.get("validator_passed_count") == 13)
check("validator_failed_count=0", f93a.get("validator_failed_count") == 0)
check("all_checks_passed_claimed=true", f93a.get("all_checks_passed_claimed") is True)

# === FIXT-093B ===
print("\n--- FIXT-093B ---")
f93b = pkg.get("fixt_093b", {})
check("task_type=fixture_update", f93b.get("task_type") == "fixture_update")
check("registered_module=false", f93b.get("registered_module") is False)
check("shared_asset_task=true", f93b.get("shared_asset_task") is True)
check("synthetic_only=true", f93b.get("synthetic_only") is True)
check("capability_value=not_applicable", f93b.get("capability_value") == "not_applicable")
check("risk_level=not_applicable", f93b.get("risk_level") == "not_applicable")
check("coverage_change_claimed=false", f93b.get("coverage_change_claimed") is False)
check("confirmed_vulnerability=false", f93b.get("confirmed_vulnerability") is False)
check("formal_finding_allowed=false", f93b.get("formal_finding_allowed") is False)
check("assessment_execution_performed=false", f93b.get("assessment_execution_performed") is False)
check("capability_engine_executed=false", f93b.get("capability_engine_executed") is False)
check("execution_results_generated=false", f93b.get("execution_results_generated") is False)
check("execution_allowed=false", f93b.get("execution_allowed") is False)
check("validator_name", f93b.get("validator_name") == "validate_fixt093b.py")
check("validator_passed_count=14", f93b.get("validator_passed_count") == 14)
check("validator_failed_count=0", f93b.get("validator_failed_count") == 0)
check("all_checks_passed_claimed=true", f93b.get("all_checks_passed_claimed") is True)

# === Phase-93F ===
print("\n--- Phase-93F ---")
p93f = pkg.get("phase_93f", {})
check("registered_module=false", p93f.get("registered_module") is False)
check("coverage_change_claimed=false", p93f.get("coverage_change_claimed") is False)
check("assessment_execution_performed=false", p93f.get("assessment_execution_performed") is False)
check("capability_engine_executed=false", p93f.get("capability_engine_executed") is False)
check("execution_results_generated=false", p93f.get("execution_results_generated") is False)
check("capability_value=not_applicable", p93f.get("capability_value") == "not_applicable")
check("risk_level=not_applicable", p93f.get("risk_level") == "not_applicable")
check("execution_allowed=false", p93f.get("execution_allowed") is False)
check("validator_name", p93f.get("validator_name") == "validate_phase93f.py")
check("validator_passed_count=17", p93f.get("validator_passed_count") == 17)
check("validator_failed_count=0", p93f.get("validator_failed_count") == 0)
reviews = p93f.get("reviews", [])
check("3 reviews", len(reviews) == 3)
for rv in reviews:
    check(f"{rv['report_id']} reviewed_commit present", rv.get("reviewed_commit") is not None)
    check(f"{rv['report_id']} execution_results_ref present", rv.get("execution_results_ref") is not None)
    check(f"{rv['report_id']} execution_results_integrity_verified=true", rv.get("execution_results_integrity_verified") is True)
    check(f"{rv['report_id']} result_scorecard_reconciled=true", rv.get("result_scorecard_reconciled") is True)
    check(f"{rv['report_id']} validator_passed_count present", rv.get("validator_passed_count") is not None)
    check(f"{rv['report_id']} validator_failed_count=0", rv.get("validator_failed_count") == 0)
    check(f"{rv['report_id']} review_outcome=candidate", rv.get("review_outcome") == "candidate")

# === Phase-93G ===
print("\n--- Phase-93G ---")
p93g = pkg.get("phase_93g", {})
check("judge_status=pending_patch_review", p93g.get("judge_status") == "pending_patch_review")
check("batch_orchestration_only=true", p93g.get("batch_orchestration_only") is True)
check("coverage_credit_granted=0", p93g.get("coverage_credit_granted") == 0)
check("registered_module=false", p93g.get("registered_module") is False)

print(f"\n{'='*60}")
print(f"TOTAL: {P}/{P+F} checks passed")
print(f"{'='*60}")
sys.exit(0 if F == 0 else 1)
