"""White-box Instrumentation and Observation Provider for LangGraph Retrieval-Coupled Target."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from src.openagentsec.adapters.observation import (
    ObservationResult,
    ObservationStatus,
)
from src.openagentsec.models.enums import ObservabilityState


class LangGraphRetrievalObservationProvider:
    """White-box observation provider capturing memory retrieval, context injection, and tool traces."""

    def __init__(self) -> None:
        self.tool_intents: List[Dict[str, Any]] = []
        self.actual_tool_executions: List[Dict[str, Any]] = []
        self.node_transitions: List[Dict[str, Any]] = []
        self.audit_events: List[Dict[str, Any]] = []
        self.retrieval_events: List[Dict[str, Any]] = []
        self.context_injections: List[Dict[str, Any]] = []
        self.decision_dependencies: List[Dict[str, Any]] = []
        self.last_model_response: Optional[str] = None
        self.last_state_snapshot: Optional[Dict[str, Any]] = None
        self.active_node: Optional[str] = None
        self._execution_counter: int = 0

    def record_node_entry(self, node_name: str, state_snapshot: Dict[str, Any]) -> None:
        """Record entry into a StateGraph node."""
        prev = self.active_node
        self.active_node = node_name
        self.last_state_snapshot = dict(state_snapshot)
        transition = {
            "from_node": prev,
            "to_node": node_name,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        self.node_transitions.append(transition)
        self.audit_events.append({
            "event_type": "NODE_TRANSITION",
            "details": transition,
            "timestamp": transition["timestamp"],
        })

    def record_retrieval_event(
        self,
        query: str,
        retrieved_memory_ids: List[str],
        retrieved_contents: List[str],
        status: str = "hit",
    ) -> None:
        """Record a memory retrieval event."""
        event = {
            "query": query,
            "retrieved_memory_ids": list(retrieved_memory_ids),
            "retrieved_contents": list(retrieved_contents),
            "retrieval_status": status,
            "retrieval_triggered": True,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        self.retrieval_events.append(event)
        self.audit_events.append({
            "event_type": "MEMORY_RETRIEVAL_EXECUTED",
            "details": event,
            "timestamp": event["timestamp"],
        })

    def record_context_injection(
        self,
        raw_stimulus: str,
        injected_memory_ids: List[str],
        synthesized_context: str,
    ) -> None:
        """Record dynamic context synthesis and injection."""
        trace = {
            "raw_stimulus": raw_stimulus,
            "injected_memory_ids": list(injected_memory_ids),
            "synthesized_context": synthesized_context,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        self.context_injections.append(trace)
        self.audit_events.append({
            "event_type": "CONTEXT_INJECTION_SYNTHESIZED",
            "details": trace,
            "timestamp": trace["timestamp"],
        })

    def record_decision_dependency(
        self,
        decision_dependency: str,
        selected_tool: str,
        causal_memory_id: Optional[str] = None,
    ) -> None:
        """Record causal dependency between retrieved memory and action decision."""
        trace = {
            "decision_dependency": decision_dependency,
            "selected_tool": selected_tool,
            "causal_memory_id": causal_memory_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
        }
        self.decision_dependencies.append(trace)
        self.audit_events.append({
            "event_type": "DECISION_DEPENDENCY_RESOLVED",
            "details": trace,
            "timestamp": trace["timestamp"],
        })

    def record_tool_intent(self, tool_name: str, args: Dict[str, Any], call_id: str) -> None:
        """Record a structured tool intent generated by the model."""
        intent = {
            "tool": tool_name,
            "args": args,
            "call_id": call_id,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "source": "model_output_intent",
        }
        self.tool_intents.append(intent)
        self.audit_events.append({
            "event_type": "TOOL_INTENT_GENERATED",
            "details": intent,
            "timestamp": intent["timestamp"],
        })

    def record_tool_execution(
        self,
        tool_name: str,
        args: Dict[str, Any],
        call_id: str,
        status: str,
        result: Any,
    ) -> None:
        """Record actual tool execution in the runtime."""
        self._execution_counter += 1
        record = {
            "execution_order": self._execution_counter,
            "tool": tool_name,
            "args": args,
            "call_id": call_id,
            "status": status,
            "result": result,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "verified_runtime_execution": True,
        }
        self.actual_tool_executions.append(record)
        self.audit_events.append({
            "event_type": "ACTUAL_TOOL_EXECUTED",
            "details": record,
            "timestamp": record["timestamp"],
        })

    def record_model_response(self, response_text: str) -> None:
        """Record final assistant response message."""
        self.last_model_response = response_text
        self.audit_events.append({
            "event_type": "MODEL_RESPONSE_GENERATED",
            "details": {"response": response_text},
            "timestamp": datetime.now(timezone.utc).isoformat(),
        })

    def get_model_response(self) -> ObservationResult[Optional[str]]:
        if self.last_model_response is None:
            return ObservationResult(
                observability=ObservabilityState.OBSERVABLE,
                status=ObservationStatus.EMPTY,
                value=None,
                source="langgraph_whitebox_instrumentation",
                reason="No model response generated yet",
            )
        return ObservationResult(
            observability=ObservabilityState.OBSERVABLE,
            status=ObservationStatus.OBSERVED,
            value=self.last_model_response,
            source="langgraph_whitebox_instrumentation",
        )

    def get_tool_trace(self) -> ObservationResult[Optional[List[Dict[str, Any]]]]:
        if not self.actual_tool_executions:
            return ObservationResult(
                observability=ObservabilityState.OBSERVABLE,
                status=ObservationStatus.EMPTY,
                value=[],
                source="langgraph_whitebox_instrumentation",
                reason="No tool executions occurred",
            )
        return ObservationResult(
            observability=ObservabilityState.OBSERVABLE,
            status=ObservationStatus.OBSERVED,
            value=list(self.actual_tool_executions),
            source="langgraph_whitebox_instrumentation",
        )

    def get_runtime_state(self) -> ObservationResult[Optional[Dict[str, Any]]]:
        if not self.node_transitions:
            return ObservationResult(
                observability=ObservabilityState.OBSERVABLE,
                status=ObservationStatus.EMPTY,
                value=None,
                source="langgraph_whitebox_instrumentation",
                reason="Graph has not executed yet",
            )
        return ObservationResult(
            observability=ObservabilityState.OBSERVABLE,
            status=ObservationStatus.OBSERVED,
            value={
                "active_node": self.active_node,
                "node_transitions": list(self.node_transitions),
                "total_transitions": len(self.node_transitions),
                "latest_snapshot": self.last_state_snapshot,
            },
            source="langgraph_whitebox_instrumentation",
        )

    def get_memory_state(self) -> ObservationResult[Optional[Dict[str, Any]]]:
        if self.last_state_snapshot is None:
            return ObservationResult(
                observability=ObservabilityState.OBSERVABLE,
                status=ObservationStatus.EMPTY,
                value={"messages": [], "message_count": 0},
                source="langgraph_whitebox_instrumentation",
                reason="No checkpoint state recorded",
            )
        msgs = self.last_state_snapshot.get("messages", [])
        return ObservationResult(
            observability=ObservabilityState.OBSERVABLE,
            status=ObservationStatus.OBSERVED,
            value={
                "messages": [str(m) for m in msgs],
                "message_count": len(msgs),
                "untrusted_context_retrieved": self.last_state_snapshot.get(
                    "untrusted_context_retrieved", False
                ),
                "retrieval_receipt": self.last_state_snapshot.get("retrieval_receipt"),
                "context_injection": self.last_state_snapshot.get("context_injection"),
                "decision_trace": self.last_state_snapshot.get("decision_trace"),
            },
            source="langgraph_whitebox_instrumentation",
        )

    def get_retrieval_trace(self) -> ObservationResult[Optional[List[Dict[str, Any]]]]:
        return ObservationResult(
            observability=ObservabilityState.OBSERVABLE,
            status=ObservationStatus.OBSERVED if self.retrieval_events else ObservationStatus.EMPTY,
            value=list(self.retrieval_events),
            source="langgraph_whitebox_instrumentation",
        )

    def get_context_injection_trace(self) -> ObservationResult[Optional[List[Dict[str, Any]]]]:
        return ObservationResult(
            observability=ObservabilityState.OBSERVABLE,
            status=ObservationStatus.OBSERVED if self.context_injections else ObservationStatus.EMPTY,
            value=list(self.context_injections),
            source="langgraph_whitebox_instrumentation",
        )

    def get_decision_dependency_trace(self) -> ObservationResult[Optional[List[Dict[str, Any]]]]:
        return ObservationResult(
            observability=ObservabilityState.OBSERVABLE,
            status=ObservationStatus.OBSERVED if self.decision_dependencies else ObservationStatus.EMPTY,
            value=list(self.decision_dependencies),
            source="langgraph_whitebox_instrumentation",
        )

    def get_audit_events(self) -> ObservationResult[Optional[List[Dict[str, Any]]]]:
        return ObservationResult(
            observability=ObservabilityState.OBSERVABLE,
            status=ObservationStatus.OBSERVED if self.audit_events else ObservationStatus.EMPTY,
            value=list(self.audit_events),
            source="langgraph_whitebox_instrumentation",
        )

    def reset(self) -> ObservationResult[bool]:
        """Reset instrumentation collectors and verify clean state."""
        self.tool_intents.clear()
        self.actual_tool_executions.clear()
        self.node_transitions.clear()
        self.audit_events.clear()
        self.retrieval_events.clear()
        self.context_injections.clear()
        self.decision_dependencies.clear()
        self.last_model_response = None
        self.last_state_snapshot = None
        self.active_node = None
        self._execution_counter = 0

        return ObservationResult(
            observability=ObservabilityState.OBSERVABLE,
            status=ObservationStatus.OBSERVED,
            value=True,
            source="langgraph_whitebox_instrumentation",
        )
